### ISSUE TITLE
No module / PYTHONPATH

### ISSUE THREAD

**Issue by RasmusFonseca** [akma327/MDContactNetworks#1]
When executing `dynamic_contact_networks.py` or `static_contact_networks.py` from a separate directory I got 
```bash
MBPro:~/Documents/GProtein_Flares/interactions $ python ~/Documents/MDContactNetworks/static_contact_networks.py  --topology ../structures/AlF3_clean.pdb --output_dir OUTPUT_AlF3/ --itype -sb -hb -vdw
Traceback (most recent call last):
  File "/Users/rfonseca/Documents/MDContactNetworks/static_contact_networks.py", line 17, in <module>
    from contact_calc import compute_contacts
  File "/Users/rfonseca/Documents/MDContactNetworks/contact_calc/compute_contacts.py", line 20, in <module>
    from contact_utils import *
ModuleNotFoundError: No module named 'contact_utils'
```
I changed the imports in the `contact_calc` package from 
```python
from contact_utils import *`
```
to
```python
from .contact_utils import *
```
(added dot for relative imports). This works on my system, but it'd be great if someone could verify that it hasn't messed up other workflows.

**Comment by akma327** [comment]
I just cloned the latest version with the .contact_utils import * command and it works normally.

Best,

Anthony


On Dec 29, 2017, at 11:29 AM, Rasmus Fonseca <notifications@github.com<mailto:notifications@github.com>> wrote:


When executing dynamic_contact_networks.py or static_contact_networks.py from a separate directory I got

MBPro:~/Documents/GProtein_Flares/interactions $ python ~/Documents/MDContactNetworks/static_contact_networks.py  --topology ../structures/AlF3_clean.pdb --output_dir OUTPUT_AlF3/ --itype -sb -hb -vdw
Traceback (most recent call last):
  File "/Users/rfonseca/Documents/MDContactNetworks/static_contact_networks.py", line 17, in <module>
    from contact_calc import compute_contacts
  File "/Users/rfonseca/Documents/MDContactNetworks/contact_calc/compute_contacts.py", line 20, in <module>
    from contact_utils import *
ModuleNotFoundError: No module named 'contact_utils'

I changed the imports in the contact_calc package from

from contact_utils import *`

to

from .contact_utils import *

(added dot for relative imports). This works on my system, but it'd be great if someone could verify that it hasn't messed up other workflows.

**Comment by RasmusFonseca** [comment]
I think this has been pretty much resolved using dots in front of imports. Ok to close?

**Comment by RasmusFonseca** [comment]
I'm closing. If anyone has issues feel free to reopen
