### ISSUE TITLE
Need some way to access number of frames in simulation

### ISSUE THREAD

**Issue by agchempa** [akma327/MDContactNetworks#10]
Currently, there's no way of determining how many frames are in the simulation after an MDContact run. For instance, if you run MDContact on pi-cation interactions, there's no guarantee that a pi-cation interaction appears in the last frame, so the number of frame cannot be determined in the output. 

This would really help with the MDCompare pipeline!

**Comment by agchempa** [comment]
Just bumping this

**Comment by akma327** [comment]
Perhaps for every computed chunk of contacts, one can output an additional parameter for the length of that chunk, then add the frame count together at the end. This still needs to be implemented

**Comment by ajvenkat** [comment]
Knowing the total number of frames in a simulation is pretty important. Without this info, the relative importance of the interactions (in terms of frequency) is hard to comprehend. Might it make sense to write out a file with the total number of frames? I understand that this file will have just one line, but this information is pretty important to have.


On Jan 29, 2018, at 3:33 PM, Anthony Ma <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps for every computed chunk of contacts, one can output an additional parameter for the length of that chunk, then add the frame count together at the end. This still needs to be implemented

**Comment by RasmusFonseca** [comment]
It's fairly common to use `#` as a comment indicator. I suggest adding a first line of the output file with 'metadata':
```
# total_frames:20 interaction_types:vdw,hb
0	hbss	A:GLN:53:NE2	A:GLN:69:OE1
0	hbss	A:GLU:60:OE2	A:SER:56:OG
0	hbss	A:GLU:60:OE2	A:GLU:63:OE1
0	hbss	A:ARG:76:NH1	A:GLU:82:OE2
...
```

**Comment by ajvenkat** [comment]
Yea, I like this idea of using '#' to describe the total number of interactions. How about a second line starting with '#' to describe what each column is?

`# total_frames:20 interaction_types:vdw,hb
#frame_num, interaction_type, atom_1, atom_2
0	hbss	A:GLN:53:NE2	A:GLN:69:OE1
0	hbss	A:GLU:60:OE2	A:SER:56:OG
0	hbss	A:GLU:60:OE2	A:GLU:63:OE1
0	hbss	A:ARG:76:NH1	A:GLU:82:OE2
...`

**Comment by agchempa** [comment]
I think the suggested solution above is a great idea. Any chance this update can be made?

**Comment by RasmusFonseca** [comment]
Fixed in https://github.com/akma327/MDContactNetworks/commit/1a4bb076943bb6fa4774084d1ac4120a9f9cc639.
