### ISSUE TITLE
Allowing user to select which combinations of contacts they want to compute at once and output into one file. 

### ISSUE THREAD

**Issue by akma327** [akma327/MDContactNetworks#12]
With latest refactoring, it seems like users are only allowed to compute one interaction type at a time (unless specifiying all-interactions flag). Would it be possible to do something like -hb -sb -pc and report all contacts of those types in one contacts.tsv file?

**Comment by RasmusFonseca** [comment]
Yes, that's possible right now. See: https://github.com/akma327/MDContactNetworks/blob/096f60dd985f16b3034e78c73d4861470ae1f7cd/dynamic_contacts.py#L211-L225

You also have the option of providing `-all`

**Comment by akma327** [comment]
Hello Rasmus,

When I run the following:
python dynamic_contacts.py --topology $top --trajectory $traj --output $out --itypes -sb -hb -ps -ts

It only computes ts, basically the itypes set seems to take only the last argument? Is my formatting not compatible with the new changes?

When running -all then the itypes is hardcoded to all types. Let me know if you get the same behavior and can modify the itype input argument command.

**Comment by RasmusFonseca** [comment]
Oups, you're right. That's because of a grammar mistake: https://github.com/akma327/MDContactNetworks/commit/fc68838ac9f87425c007ab98356857ddea9eb66a

```
python dynamic_contacts.py --topology $top --trajectory $traj --output $out -sb -hb -ps -ts
```
should give you what you want now. Note: `--itypes` is not necessary.

**Comment by akma327** [comment]
Awesome thanks!
