### ISSUE TITLE
Long-range van der waals contacts

### ISSUE THREAD

**Issue by ajvenkat** [akma327/MDContactNetworks#13]
The van der Waals interactions output files of MDcontacts are huge and noisy when it comes to information content. The main reason for this is that a majority of these contacts are between:
1. atoms within the same residue or 
2. atoms within residues that are proximal in sequence (short-range contacts). 

For most practical purposes though, it is the long range van der waals contacts that are useful, i.e. van der waals contacts between residues that are greater than four amino acids apart in sequence. 

Therefore, would it be possible to have a flag that allows us to compute long range van der waals contacts, and make this the default van der waals output?

**Comment by RasmusFonseca** [comment]
Good point. I think for most use-cases it'd make sense to only report interactions between residue id `i` and `i±x` and beyond where `x=2`. If we simply make `x` a tunable parameter with default value 2 then its only a very trivial change to the command line arguments.

**Comment by RasmusFonseca** [comment]
Fixed in https://github.com/akma327/MDContactNetworks/commit/c1c000e693bcc0ad53d1e796801e9d909e00643d by adding `--vdw_res_diff` argument.

**Comment by akma327** [comment]
This is great Rasmus, do you mind adding a short blurb about vdw_res_diff argument in the readme? Feel free to close after.

**Comment by RasmusFonseca** [comment]
Fixed by https://github.com/akma327/MDContactNetworks/commit/658c2de765d62328f21a7044cd0dafdb02e518b8 and also went over the README .. especially the last parts.
