### ISSUE TITLE
--sele default

### ISSUE THREAD

**Issue by RasmusFonseca** [akma327/MDContactNetworks#15]
Currently this is the documentation for the `--sele` argument:

    --sele SELECTION VMD selection query to compute contacts in specified 
                     region of protein [default = None]

Wouldn't a more accurate default be `"protein"`?

**Comment by akma327** [comment]
Hmm yeah, a better default would be to have default = "protein"

There are some stylistic improvements that can be done. Right now it's an 
if (sele == None):
    Compute contacts for protein
else:
    Compute contacts for protein and sele.

**Comment by RasmusFonseca** [comment]
Got it. Ill update the readme.

**Comment by akma327** [comment]
Sounds good. But just to clarify that some minor code changes need to go along with it. If default is set to "protein" right now, how the code interprets would be query "protein and protein". 

(ie hbonds.py lines 60-70)

**Comment by RasmusFonseca** [comment]
Oh now I see what you're saying: "protein" is more than a default, it's enforced in the code. Still, "protein and protein" is the same as "protein", so it'd not be wrong to update the readme and leave the code untouched. I'll let you make a call.

**Comment by akma327** [comment]
Yeah, I agree, we can proceed to update readme for now, since behavior wise we are defaulting to protein by hard coding.
