### ISSUE TITLE
Atomic level info for stacking interactions

### ISSUE THREAD

**Issue by RasmusFonseca** [akma327/MDContactNetworks#2]
It's not clear from the documentation if atomic-level information is available for all interaction types and if so, which atom is indicated for e.g. pi-stacking.

**Comment by akma327** [comment]
Based on our latest meeting, picking the most distal ring atom on the sidechain residue may be the way to go. Open to other definitions as well, but we've settled for just one atom representation.

**Comment by ajvenkat** [comment]
Yes, we've settled for just one atom representation. My recommendation would be the CG atom. That way it is consistent across Phe, Tyr and Trp.

**Comment by RasmusFonseca** [comment]
No strong opinion, but using CG is easier to implement and document so I'd be happy with that.

**Comment by akma327** [comment]
Let's just keep it consistent and simple with CG and stick with that for now.

**Comment by RasmusFonseca** [comment]
Great. I hope it's ok I'm leaving this open until we have actually implemented it and added to documentation.

**Comment by akma327** [comment]
Just implemented to CG atom representation for all aromatic interactions. We'll keep in mind to add all the changes to updated readme.

**Comment by akma327** [comment]
Updated documentation
