### ISSUE TITLE
output_additional.py not used anymore

### ISSUE THREAD

**Issue by RasmusFonseca** [akma327/MDContactNetworks#4]
.. if we're certain that we don't need this functionality anymore it should probably be removed.

**Comment by RasmusFonseca** [comment]
Bump. @akma are we OK to remove `output_additional.py`?

**Comment by akma327** [comment]
Yes, if its not used I would move it out of the contact_calc repo. It was written by Augustine? So perhaps move to MDCompare or have him save a copy locally.
