### ISSUE TITLE
Latest refactoring introduced bug such that the output is skipped every 100, or has only 100 max frames output. 

### ISSUE THREAD

**Issue by akma327** [akma327/MDContactNetworks#6]
Many contacts are jumbled together into single frame. Tool in the latest commit is non functional. 

Went back to testing the original version: commit 469c227b0b3d3f0609e0b0a70aa240b2aa790a26
and got accurate results with every frame shown (ie a 10000 frame simulation has 10000 frames with accurate contacts). In latest version, get 100 frames with garbled output. 

Latest functional build may have been: commit ad4341b2ce7c461878e479932c339a30fa6ca92e

**Comment by RasmusFonseca** [comment]
Working on this now. Noticed that if you set `TRAJ_FRAG_SIZE = 3` in the July 26 version then it also generates more frames than are in the simulation (20 in the case of the 5xnd example)

**Comment by RasmusFonseca** [comment]
Ah .. the ones with 1 and 3 frames makes sense because they're the ones where it's trying to read  beyond the last frame. Remaining question is, why does it read 5 frames when we're telling it to read from frame 0 to 3?

**Comment by RasmusFonseca** [comment]
I think this is fixed now. @akma327 could you test on a large trajectory. 

If I set `TRAJ_FRAG_SIZE = 3` in the July 26 version it doesn't work. Some interactions gets offset. The newest commit seems to works on the 5xnd example with both `TRAJ_FRAG_SIZE` set to 3 and 100 by manual inspection in pymol and by comparison with the July26 version with large `TRAJ_FRAG_SIZE`.

**Comment by RasmusFonseca** [comment]
Bump. I think this is fixed. @akma327 .. will you closed if you consider this resolved?
