### ISSUE TITLE
Computing hb contacts on simulations without waters may lead to crash

### ISSUE THREAD

**Issue by akma327** [akma327/MDContactNetworks#7]
Currently computing hbonds means computing hbss, hbsb, hbbb, wb, wb2. In simulations without waters there is a bug that causes run to crash because wb and wb2 in reality should have no contacts but, there are out of index errors because of empty array. Can fix this easily after restoring build.

**Comment by RasmusFonseca** [comment]
Bump .. restoring build? If you have an example I can look at it.

**Comment by akma327** [comment]
I'll try to dig up an example and see if this bug is still there, but may know the logic behind the crash.

**Comment by akma327** [comment]
Seems like this bug was resolved from latest refactor.

**Comment by RasmusFonseca** [comment]
Lovely :sunglasses:
