### ISSUE TITLE
Missing info in README documentation

### ISSUE THREAD

**Issue by RasmusFonseca** [akma327/MDContactNetworks#9]
I've given the README an overhaul and it'd be good if someone else checked it. We also need to address the following points:

- [x] Last section on generating dynamic networks should be updated to reflect new arguments and output-file
- [x] Clear and formal definition of output-format. It's especially important that water-mediated interactions are explained as they differ a bit from the format of the other interaction types.

**Comment by akma327** [comment]
I update the example on readme to have more contact types and added a blurb regarding water bridges. Feel free to add or update this part as well.
